# Generated by Django 5.1.4 on 2025-04-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceryitem',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
    ]
